@startuml

digraph g {
graph [ordering=out];
node [shape=rectangle];
n[label = "+"];
n0[label = "/"];
n00[label = "Max"];
n000[label = "*"];
n0000[label = "WIQ"];
n000 -> n0000;
n0001[label = "TWT"];
n000 -> n0001;
n00 -> n000;
n001[label = "/"];
n0010[label = "WIQ"];
n001 -> n0010;
n0011[label = "TWT"];
n001 -> n0011;
n00 -> n001;
n0 -> n00;
n01[label = "Max"];
n010[label = "+"];
n0100[label = "NIQ"];
n010 -> n0100;
n0101[label = "MRT"];
n010 -> n0101;
n01 -> n010;
n011[label = "/"];
n0110[label = "TTIQ"];
n011 -> n0110;
n0111[label = "TIS"];
n011 -> n0111;
n01 -> n011;
n0 -> n01;
n -> n0;
n1[label = "*"];
n10[label = "-"];
n100[label = "MRT"];
n10 -> n100;
n101[label = "NIQ"];
n10 -> n101;
n1 -> n10;
n11[label = "Min"];
n110[label = "MRT"];
n11 -> n110;
n111[label = "WIQ"];
n11 -> n111;
n1 -> n11;
n -> n1;
}

@enduml